### ISSUE TITLE
()s disappear in Markdown links

### ISSUE THREAD

**Issue by davidainman** [PaprikaSteiger/ooaclld#15]
Hi Robert,

I am back to working on this repo, and will hopefully be working on it more regularly as the writing for the data publication picks up steam. I have noted that ()s inside Markdown links are deleted. This can be seen in e.g. contributions/Lat in the second paragraph under "Why?"

The markdown reads:

`[Maddieson (2013)](Source#cldf:maddieson2013wals8) focuses on ...`

But the HTML output is:

> Maddieson 2013 focuses on ...

This is not normal markdown behavior to my knowledge, so I wonder if the clld-markdown-plugin is ignoring ()s in URLs.

**Comment by xrotwang** [comment]
I'll try to look into this tomorrow. I think, the CLDF Markdown processing replaces not only the link but also the label with a normalized label created from the BibTeX record. If so, I think switching to preserving an existing label as default would be the simplest solution - I don't want to implement all the `\citet, \citep, ...` varieties available in LaTeX ...

**Comment by xrotwang** [comment]
clld-markdown-plugin v0.5 should fix this issue - if you set the corresponding [configuration option](https://github.com/clld/clld-markdown-plugin?tab=readme-ov-file#configuration), `"keep_link_labels": True` in https://github.com/PaprikaSteiger/ooaclld/blob/9c791cd870540910acf0aec4dae9c861ece23acb/ooaclld/ooaclld/__init__.py#L89-L99

**Comment by davidainman** [comment]
I have updated to v0.5 and updated the configuration to include `"keep_link_labels": True` (see [here](https://github.com/PaprikaSteiger/ooaclld/pull/16/commits/9a223ed581191e17bc76b03531442f73a2590ca5) in pull request #16), but I am not yet seeing the expected behavior.

<img width="655" alt="image" src="https://github.com/PaprikaSteiger/ooaclld/assets/6406484/45dd74e3-4b48-400e-97ad-3e511931fc6d">
<img width="625" alt="image" src="https://github.com/PaprikaSteiger/ooaclld/assets/6406484/d7871de3-4c0f-44be-9a44-8b7d00683d41">

I have double-checked my clld-markdown-plugin version, and I believe it is correct:

> (base) david@DIMB ooaclld % pip show clld_markdown_plugin
> Name: clld-markdown-plugin
> Version: 0.5.0
> Summary: Render CLDF markdown in clld apps.
> Home-page: https://github.com/clld/clld-markdown-plugin
> Author: Robert Forkel, Florian Matter
> Author-email: robert_forkel@eva.mpg.de, florianmatter@gmail.com
> License: 
> Location: /Users/david/anaconda3/lib/python3.11/site-packages
> Requires: clld, clldutils, markdown, pycldf

**Comment by xrotwang** [comment]
Hm. Works on my end:
![Screenshot 2024-03-22 at 08-53-50 None - Feature Set Laterals](https://github.com/PaprikaSteiger/ooaclld/assets/870184/ced345a2-0af2-412c-a07a-1e296675a1c5)

That's on branch `main`, after recreating the db running `clld initdb development.ini ../cldf/StructureDataset-metadata.json`.

**Comment by xrotwang** [comment]
Here's the relevant packages:
```
$ pip freeze | grep clld
clld==10.0.0
clld-glottologfamily-plugin==4.0.0
clld-markdown-plugin==0.5.0
clldmpg==4.3.0
clldutils==3.22.0
-e git+https://github.com/PaprikaSteiger/ooaclld@ea7c1043d4f7d4949a0cffc8b229ad62d1fb1f32#egg=ooaclld&subdirectory=ooaclld
```

**Comment by davidainman** [comment]
Thanks for the confirmation, Robert -- I had two versions of the markdown on my laptop, and was managing to load the wrong one. Resolved.

**Comment by xrotwang** [comment]
It was good to see that I can still run the project locally. This should help going forward :)
