### ISSUE TITLE
Partial string match search for ID columns

### ISSUE THREAD

**Issue by davidainman** [PaprikaSteiger/ooaclld#20]
I have noticed that IdCol types do not by default do not allow for searches according to partial matches in tables. E.g., the Glottocode column of the Languages table (URL/languages) does not return any match to a string search unless it is exact.

I attempted to change the IdCol of database.py:113 to LinkCol, i.e.

`IdCol(self, "ID", sTitle="Glottocode", sClass="left", model_col=OOALanguage.id),`

to

`LinkCol(self, "ID", sTitle="Glottocode", sClass="left", model_col=OOALanguage.id)`

But this (unexpectedly) changed the displayed data as well, displaying OOALanguage.name instead of OOAlanguage.id.

Is it possible for me to allow for the search behavior of IdCols to behave as in LinkCol and Col types?

**Comment by xrotwang** [comment]
You can subclass `LinkCol`, overwriting `get_attrs` like `IdCol` does, see https://github.com/clld/clld/blob/b03984e8b88097c6f6247858207a573e070f85ff/src/clld/web/datatables/base.py#L244-L245
Then you use the derived class in the table's `col_defs` method.

**Comment by davidainman** [comment]
Works beautifully, will resolve with the next pull request. Thanks!

**Comment by davidainman** [comment]
Resolved with pull #24
