### ISSUE TITLE
Search functions on individual parameters generate sql errors

### ISSUE THREAD

**Issue by davidainman** [PaprikaSteiger/ooaclld#23]
All of the search boxes on individual parameters pages (e.g. parameters/Lat-01) are generating SQL errors and then a visual hang (and add to the queue on the server). I believe there is something incorrect with how OOAValue class is being created in initializedb.py:235, but I really do not know where to begin debugging this, I am sorry to say.

**Comment by xrotwang** [comment]
Yeah, the way values are related to valuesets in initializedb looks funky. Will need to take a detailed look. Possibly tomorrow.
