### ISSUE TITLE
Rendering maps from features

### ISSUE THREAD

**Issue by davidainman** [PaprikaSteiger/ooaclld#5]
[xrotwang](https://github.com/xrotwang) (Hi!) I'm trying to generate maps for individual features following your example in Wals3. I am instantiating the following code in maps.py:

```
from clld.web.maps import ParameterMap, Map, Layer, CombinationMap
from clld.web.util.helpers import JS, map_marker_img

class FeatureMap(ParameterMap):
    def get_options(self):
        return {
            'icon_size': 20,
            'max_zoom': 9,
            'worldCopyJump': True,
            'zoom': 5,
            'info_query': {'parameter': self.ctx.pk}}

def includeme(config):
    config.register_map('parameter', FeatureMap)
```

However, the above code doesn't seem to do much, and I still get an empty leaflet map when I access something (e.g., parameters/Lat-02#0/0/0). By modifying icon_size I can change the icon size on the map (visible from the drop-down, nothing is rendered), and I can confirm that at least some fo the data is actually loaded, as the legend shows the correct number of states, though again nothing is loaded onto the map. The values we have in our table I think match wals, with Latitude and Longitude. I assume something beyond maps.py needs to be altered but I have not been able to figure this out poking around in the Wals3 code by myself.

**Comment by PaprikaSteiger** [comment]
Hi Robert, @xrotwang

Sorry for never answering again to your reply. My contract ended and now I'm back for a month to finish the project. So you'll probably get pinned a few times this month :/

 Our values look like this:
`"ID","LanguageID","ParameterID","CodeID","Value","Remark","Source","Coder"`
`"abkh1244_Appr-02","abkh1244","Appr-02","NA_Appr-02","NA",,"hewitt1979abkhaz","DP"`

Our values are like the ones from Wals in the sense that we would need one ValueSet per Value.
I read the Values and ValueSets into the DB like this (I'm aware that I do not add a proper foreign key as domainelement_pk) :
(current_contribution is 'Appr' from the ValueID)
```  
for c, row in enumerate(tqdm(ds.iter_rows('ValueTable'), desc="Processing values")):
        data.add(common.ValueSet, row['ID'],
                 id=row['ID'],
                 language_pk=data["OOALanguage"][row["LanguageID"]].pk,
                 parameter_pk=data["OOAParameter"][row["ParameterID"]].pk,
                 contribution_pk=data["OOAFeatureSet"][current_contribution].pk,
                 #TODO: check that all values in the same valueset have the same source. If not, discuss with david
                 source="",
                 )
        DBSession.flush()
        data.add(models.OOAValue, row["ID"],
                 id=row["ID"],
                 valueset_pk=data["ValueSet"][current_valueset_id].pk,
                 # TODO: insert real pk fore CodeID (Codes never used so far; Code=common.DomainElement)
                 domainelement_pk=row["CodeID"],
                 value=row["Value"],
                 remark=row["Remark"],
                 coder=";".join(row["Coder"]),
                 )
        DBSession.flush()
```

As a sanity check, that I don't get stuck within the query, I print out the two lines `language query started` and
`language query ended`. So I just copied the [source code](https://github.com/clld/clld/blob/master/src/clld/web/datatables/value.py) and added the two print statements. (I copied the complete base_query function including the constraints)
```
        if self.language:
            print("language query started")
            query = query.join(ValueSet.parameter)
            query = query.filter(ValueSet.language_pk == self.language.pk)
            print("language query ended")
            return query
```

But the page keeps 'processing' (I waited for more than 10 minutes). I don't get an error in the console and no error in the terminal. The query is executed immediately without any errors. Do you have any idea what is going on here? (Screenshot after roughly 5 min of waiting) I also tried initializing the DB making sure that Values and ValueSets do not have the same ID (`row['ID']`), although I wouldn't expect it to cause any problems when the IDs are identical. 

![image](https://user-images.githubusercontent.com/45519367/223809066-9aae0ecb-b2ad-4208-94ce-0cc9debc8ede.png)

**Comment by xrotwang** [comment]
A couple of things: 

First, it looks like you add **all** Values to the same ValueSet

> valueset_pk=data["ValueSet"][current_valueset_id].pk

The `current_valueset_id` doesn't seem to change within the loop you pasted above.

Second, the query is **not** executed between your two print statements. It is just put together. The first time the query is executed is here:
https://github.com/clld/clld/blob/837351371d150f43c4945140d3ec1f2027375f6a/src/clld/web/datatables/base.py#L549

Third, rather than assigning garbage to an argument expecting a primary key, you should pass `domainelement_pk=None`.

Also, I'd rather look at the complete code than trying to figure out what's going on from selected snippets.

**Comment by xrotwang** [comment]
`domainelement_pk=row["CodeID"]` is garbage in the sense that `row['CodeID']` could only be a valid primary key in the domainelement table by accident.

**Comment by xrotwang** [comment]
It seems the code works now, doesn't it?

**Comment by PaprikaSteiger** [comment]
It worked on your end and for one specific language all the corresponding Values were displayed?

I deleted and created the database before I pushed the code previous to me comment above and it didn't show the Values after 10 minutes. I just deleted and re-created the database again and no Values are displayed.

**Comment by PaprikaSteiger** [comment]
I get some errors when integrating the pyramid-debuggertool (DetachedInstanceError: Instance <xxx> is not bound to a Session; attribute refresh operation cannot proceed).

**Comment by xrotwang** [comment]
You have to comment out `pyramid_tm` when running with `pyramid_debugtoolbar`.

**Comment by xrotwang** [comment]
What does `git status` say on your end? Maybe you have old stuff lingering on your machine somewhere?

**Comment by PaprikaSteiger** [comment]
I'm up to date. Just added `pyramid_debugtoolbar` to `development.ini` (before I used `config.include('pyramid_debugtoolbar') `in `__init__.py`
```
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   development.ini


```

**Comment by PaprikaSteiger** [comment]
debugger:
![image](https://user-images.githubusercontent.com/45519367/224085156-86c8c4fe-b00f-44f0-bbd0-d326b445d7ab.png)

But still processing:
![image](https://user-images.githubusercontent.com/45519367/224085214-3b210005-d08a-49d8-893a-49f0a52946a1.png)

**Comment by xrotwang** [comment]
What URL do you use to access the app?

**Comment by xrotwang** [comment]
And what does `pip freeze` say?

**Comment by PaprikaSteiger** [comment]
Url looks like that : `http://127.0.0.1:6543/languages/bert1248`

I just checked for updates in clld:
```
Installing collected packages: clldutils, clld
  Attempting uninstall: clldutils
    Found existing installation: clldutils 3.12.0
    Uninstalling clldutils-3.12.0:
      Successfully uninstalled clldutils-3.12.0
  Attempting uninstall: clld
    Found existing installation: clld 9.2.1
    Uninstalling clld-9.2.1:
      Successfully uninstalled clld-9.2.1
Successfully installed clld-10.0.0 clldutils-3.19.0

```

pip freeze:
````
appdirs==1.4.4
arrow==1.2.2
attrs==21.4.0
Babel==2.10.3
beautifulsoup4==4.11.1
binaryornot==0.4.4
black==23.1.0
bs4==0.0.1
certifi==2022.6.15
chardet==5.0.0
charset-normalizer==2.1.0
cldfcatalog==1.5.1
cldfzenodo==0.2.0
click==8.1.3
clld==10.0.0
clld-glottologfamily-plugin==4.0.0
clldmpg==4.2.0
clldutils==3.19.0
colorama==0.4.5
colorlog==6.6.0
cookiecutter==2.1.1
csvw==3.0.0
gitdb==4.0.9
GitPython==3.1.27
greenlet==1.1.2
html5lib==1.1
hupper==1.10.3
idna==3.3
importlib-metadata==4.12.0
isodate==0.6.1
Jinja2==3.1.2
jinja2-time==0.2.0
language-tags==1.1.0
latexcodec==2.0.1
linglit==1.1.0
lxml==4.9.1
Mako==1.2.1
Markdown==3.4.1
MarkupSafe==2.1.1
mypy-extensions==1.0.0
nameparser==1.1.1
newick==1.3.2
-e git+git@github.com:PaprikaSteiger/ooaclld.git@46337f32dc29e6bbd007e00e789fd171f477d43c#egg=ooaclld&subdirectory=ooaclld
packaging==23.0
paginate==0.5.6
PasteDeploy==2.1.1
pathspec==0.11.0
plaster==1.0
plaster-pastedeploy==0.7
platformdirs==3.1.0
purl==1.6
pybtex==0.24.0
pycldf==1.27.0
pycountry==22.3.5
pyglottolog==3.9.0
Pygments==2.14.0
pyigt==2.0.0
pylatexenc==2.10
pyparsing==3.0.9
pyramid==2.0
pyramid-debugtoolbar==4.10
pyramid-mako==1.1.0
pyramid-tm==2.5
python-dateutil==2.8.2
python-slugify==6.1.2
pytz==2022.1
PyYAML==6.0
rdflib==6.1.1
regex==2022.7.9
requests==2.28.1
rfc3986==1.5.0
segments==2.2.1
six==1.16.0
smmap==5.0.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.39
tabulate==0.8.10
termcolor==1.1.0
TexSoup==0.3.1
text-unidecode==1.3
thefuzz==0.19.0
tomli==2.0.1
tqdm==4.64.0
transaction==3.0.1
translationstring==1.4
typing-extensions==4.5.0
Unidecode==1.3.4
uritemplate==4.1.1
urllib3==1.26.10
venusian==3.0.0
waitress==2.1.2
webassets==2.0
webencodings==0.5.1
WebHelpers2==2.0
WebOb==1.8.7
Whoosh==2.7.4
zipp==3.8.1
zope.deprecation==4.4.0
zope.interface==5.4.0
zope.sqlalchemy==1.6

```

**Comment by xrotwang** [comment]
Hm. Looks ok to me. Maybe you can try running the whole setup in a fresh virtualenv?

**Comment by PaprikaSteiger** [comment]
I will do that tomorrow and update you.

**Comment by PaprikaSteiger** [comment]
Unfortunately no luck.
I set up a new project (pyCharm), installed all the dependencies and pulled from git. 
I also tried a different browser just to be sure. It seems that the task gets somehow queued now. In the pryamid debugger everything seems alright (tabs SQLAlchemy and Renders)
```
Starting server in PID 10052.
2023-03-10 14:23:34,355 INFO  [waitress][MainThread] Serving on http://127.0.0.1:6543
2023-03-10 14:24:59,355 WARNI [waitress.queue][MainThread] Task queue depth is 1
```

I discovered something very strange. So far I had set up one static page: featuresets/laterals (there is only a static page for laterals so far; name is the link column) On Wednesday this was still working and I did not change anything. Now, even this static page cannot be displayed. The resources are shown correctly in the console:
![image](https://user-images.githubusercontent.com/45519367/224328487-1a3a9a4b-bcc3-40db-93ba-6babd8bfda21.png)
Even if I click on a featureset name that does not have a static page, nothing happened, whereas before it used to display an error.

There seems to be something profoundly wrong when rendering the stuff on my end. I'm currently double checking with David if it works on his end or not.
`waitress==2.1.2`

**Comment by PaprikaSteiger** [comment]
Values are displayed correctly for a language on Davids machine. The static page is not.

**Comment by PaprikaSteiger** [comment]
I rolled back to this commit `75773b432ad8df2039673c9b84bc93bf894d5df3` from Wednesday when languages were displayed (using different code though). I kept my current venv and it's dependencies.
Languages and the static page were displayed correctly after rolling back to that commit.

**Comment by PaprikaSteiger** [comment]
@xrotwang Sorry for spaming you.
However, I switched from my Windows (with not that much computing power) to my MacBook.

**Comment by xrotwang** [comment]
Ah, good to know it's working for you now (somewhat). You'll deploy to linux anyway, I guess? I haven't heard about such problems with windows before. So if you happen to figure it out, I'd be interested to know.
