### ISSUE TITLE
Long loading time for static pages

### ISSUE THREAD

**Issue by PaprikaSteiger** [PaprikaSteiger/ooaclld#7]
Hi @xrotwang 
The `.html` of the static pages resides in `cldf/docs` and I render it [here](https://github.com/PaprikaSteiger/ooaclld/blob/250c3f26f88afd35374042954e86d0ddf3f9f6d6/ooaclld/ooaclld/templates/contribution/detail_html.mako#L1-L13).

Do you have any idea, why it takes ages to load and render the static pages? It takes roughly 7 minutes!
From Pyramid_debugger:

![image](https://user-images.githubusercontent.com/45519367/230785008-fab24c4b-6d29-48c5-bedf-7ba31d6c4d11.png)

![image](https://user-images.githubusercontent.com/45519367/230785154-9f10e51f-d2a2-4605-af19-2bba99a5a167.png)

### sql query
Time: 346194.29
Action: SELECT EXPLAIN
Params: ('Lat',)
Query:
`SELECT contribution.pk AS contribution_pk, contribution.jsondata AS contribution_jsondata, contribution.polymorphic_type AS contribution_polymorphic_type, contribution.id AS contribution_id, contribution.name AS contribution_name, contribution.description AS contribution_description, contribution.markup_description AS contribution_markup_description, contribution.date AS contribution_date, ooafeatureset.pk AS ooafeatureset_pk, ooafeatureset.featureset_id AS ooafeatureset_featureset_id, ooafeatureset.domains AS ooafeatureset_domains, ooafeatureset.authors AS ooafeatureset_authors, ooafeatureset.contributors AS ooafeatureset_contributors, ooafeatureset.filename AS ooafeatureset_filename, contribution_data_1.pk AS contribution_data_1_pk, contribution_data_1.jsondata AS contribution_data_1_jsondata, contribution_data_1."key" AS contribution_data_1_key, contribution_data_1.value AS contribution_data_1_value, contribution_data_1.ord AS contribution_data_1_ord, contribution_data_1.object_pk AS contribution_data_1_object_pk, source_1.pk AS source_1_pk, source_1.jsondata AS source_1_jsondata, source_1.polymorphic_type AS source_1_polymorphic_type, source_1.id AS source_1_id, source_1.name AS source_1_name, source_1.description AS source_1_description, source_1.markup_description AS source_1_markup_description, source_1.glottolog_id AS source_1_glottolog_id, source_1.google_book_search_id AS source_1_google_book_search_id, source_1.bibtex_type AS source_1_bibtex_type, source_1.author AS source_1_author, source_1.year AS source_1_year, source_1.title AS source_1_title, source_1.type AS source_1_type, source_1.booktitle AS source_1_booktitle, source_1.editor AS source_1_editor, source_1.pages AS source_1_pages, source_1.edition AS source_1_edition, source_1.journal AS source_1_journal, source_1.school AS source_1_school, source_1.address AS source_1_address, source_1.url AS source_1_url, source_1.note AS source_1_note, source_1.number AS source_1_number, source_1.series AS source_1_series, source_1.volume AS source_1_volume, source_1.publisher AS source_1_publisher, source_1.organization AS source_1_organization, source_1.chapter AS source_1_chapter, source_1.howpublished AS source_1_howpublished, source_1.year_int AS source_1_year_int, source_1.startpage_int AS source_1_startpage_int, source_1.pages_int AS source_1_pages_int, contributionreference_1.pk AS contributionreference_1_pk, contributionreference_1.jsondata AS contributionreference_1_jsondata, contributionreference_1."key" AS contributionreference_1_key, contributionreference_1.description AS contributionreference_1_description, contributionreference_1.contribution_pk AS contributionreference_1_contribution_pk, contributionreference_1.source_pk AS contributionreference_1_source_pk, parameter_1.pk AS parameter_1_pk, parameter_1.jsondata AS parameter_1_jsondata, parameter_1.polymorphic_type AS parameter_1_polymorphic_type, parameter_1.id AS parameter_1_id, parameter_1.name AS parameter_1_name, parameter_1.description AS parameter_1_description, parameter_1.markup_description AS parameter_1_markup_description, ooaparameter_1.pk AS ooaparameter_1_pk, ooaparameter_1.featureset_pk AS ooaparameter_1_featureset_pk, ooaparameter_1.featureset_name AS ooaparameter_1_featureset_name, ooaparameter_1.question AS ooaparameter_1_question, ooaparameter_1.datatype AS ooaparameter_1_datatype, ooaparameter_1.visualization AS ooaparameter_1_visualization, valueset_1.pk AS valueset_1_pk, valueset_1.jsondata AS valueset_1_jsondata, valueset_1.polymorphic_type AS valueset_1_polymorphic_type, valueset_1.id AS valueset_1_id, valueset_1.description AS valueset_1_description, valueset_1.markup_description AS valueset_1_markup_description, valueset_1.language_pk AS valueset_1_language_pk, valueset_1.parameter_pk AS valueset_1_parameter_pk, valueset_1.contribution_pk AS valueset_1_contribution_pk, valueset_1.source AS valueset_1_source, domainelement_1.pk AS domainelement_1_pk, domainelement_1.jsondata AS domainelement_1_jsondata, domainelement_1.polymorphic_type AS domainelement_1_polymorphic_type, domainelement_1.id AS domainelement_1_id, domainelement_1.name AS domainelement_1_name, domainelement_1.description AS domainelement_1_description, domainelement_1.markup_description AS domainelement_1_markup_description, domainelement_1.parameter_pk AS domainelement_1_parameter_pk, domainelement_1.number AS domainelement_1_number, domainelement_1.abbr AS domainelement_1_abbr, value_1.jsondata AS value_1_jsondata, value_1.polymorphic_type AS value_1_polymorphic_type, value_1.id AS value_1_id, value_1.name AS value_1_name, value_1.description AS value_1_description, value_1.markup_description AS value_1_markup_description, value_1.pk AS value_1_pk, value_1.valueset_pk AS value_1_valueset_pk, value_1.domainelement_pk AS value_1_domainelement_pk, value_1.frequency AS value_1_frequency, value_1.confidence AS value_1_confidence, ooavalue_1.pk AS ooavalue_1_pk, ooavalue_1.remark AS ooavalue_1_remark, ooavalue_1.value AS ooavalue_1_value, ooavalue_1.code_id AS ooavalue_1_code_id, ooavalue_1.coder AS ooavalue_1_coder 
FROM contribution LEFT OUTER JOIN ooafeatureset ON contribution.pk = ooafeatureset.pk LEFT OUTER JOIN contribution_data AS contribution_data_1 ON contribution.pk = contribution_data_1.object_pk LEFT OUTER JOIN (contributionreference AS contributionreference_1 JOIN source AS source_1 ON source_1.pk = contributionreference_1.source_pk) ON contribution.pk = contributionreference_1.contribution_pk LEFT OUTER JOIN (valueset AS valueset_1 JOIN (parameter AS parameter_1 LEFT OUTER JOIN ooaparameter AS ooaparameter_1 ON parameter_1.pk = ooaparameter_1.pk) ON parameter_1.pk = valueset_1.parameter_pk) ON contribution.pk = valueset_1.contribution_pk LEFT OUTER JOIN (value AS value_1 LEFT OUTER JOIN ooavalue AS ooavalue_1 ON value_1.pk = ooavalue_1.pk) ON valueset_1.pk = value_1.valueset_pk LEFT OUTER JOIN domainelement AS domainelement_1 ON domainelement_1.pk = value_1.domainelement_pk 
WHERE contribution.id = ? ORDER BY contribution_data_1.ord, valueset_1.parameter_pk, value_1.frequency DESC, value_1.confidence, value_1.pk`

**Comment by xrotwang** [comment]
The context object loaded for a contribution details page is a `Contribution` instance. For this model, a couple related attributes are loaded by default, see
https://github.com/clld/clld/blob/837351371d150f43c4945140d3ec1f2027375f6a/src/clld/web/app.py#L242-L264
So, e.g., if you attach all ValueSets in your db to the same Contribution this will result in loading all of these by default when rendering the Contribution details page.

You can change that behaviour by providing a custom context factory, as is done here
https://github.com/clld/acd/blob/09395c6b87a096850ad539965c036b110f5c57d6/acd/__init__.py#L35-L45
Note that in addition to defining the query factory, you have to register it, like here
https://github.com/clld/acd/blob/09395c6b87a096850ad539965c036b110f5c57d6/acd/__init__.py#L125

In your case, you could just define it as
```python
class CtxFactory(CtxFactoryQuery):
    def refined_query(self, query, model, req):
        if model == Contribution:
            query = query.options()
        return query
```

**Comment by PaprikaSteiger** [comment]
Thanks a lot, Robert!
